/** Auto-generated by scripts/generate-sitemap.mjs — do not edit. */
export const SITEMAP_LASTMOD = "2026-07-30";
export const SITEMAP_FINGERPRINT = "967f58caf0eac615c676704f19bbaba39330aeb7d3ad7f1fe06fa45b64922c6a";
export const INDEXNOW_KEY_PUBLIC = "7d0f518c1ef63ea96d97d6ed2fc6558e";
export const SITEMAP_URL_COUNT = 13;
export const SITEMAP_INDEX_URL = "https://billmaniac.win/sitemap.xml";
export const SITEMAP_PAGES_URL = "https://billmaniac.win/sitemap.xml";
export const SITEMAP_IMAGES_URL = "https://billmaniac.win/sitemap-images.xml";
