/** Auto-generated by scripts/generate-sitemap.mjs — do not edit. */
export const SITEMAP_LASTMOD = "2026-08-01";
export const SITEMAP_FINGERPRINT = "0841978157f51ef77c335cab1f5816d1ef3c31708792311d55dc4f2b6b8d7a3e";
export const INDEXNOW_KEY_PUBLIC = "7d0f518c1ef63ea96d97d6ed2fc6558e";
export const SITEMAP_URL_COUNT = 13;
export const SITEMAP_INDEX_URL = "https://billmaniac.win/sitemap.xml";
export const SITEMAP_PAGES_URL = "https://billmaniac.win/sitemap.xml";
export const SITEMAP_IMAGES_URL = "https://billmaniac.win/sitemap-images.xml";
