/** Auto-generated by scripts/generate-sitemap.mjs — do not edit. */
export const SITEMAP_LASTMOD = "2026-07-29";
export const SITEMAP_FINGERPRINT = "14c8a42b7b4371d6c67cceff90383bfba939d94689b21334d567c43d91bc3054";
export const INDEXNOW_KEY_PUBLIC = "7d0f518c1ef63ea96d97d6ed2fc6558e";
export const SITEMAP_URL_COUNT = 13;
export const SITEMAP_INDEX_URL = "https://billmaniac.win/sitemap.xml";
export const SITEMAP_PAGES_URL = "https://billmaniac.win/sitemap.xml";
export const SITEMAP_IMAGES_URL = "https://billmaniac.win/sitemap-images.xml";
