#!/usr/bin/env node
/**
 * Regenerates dist/sitemap.xml + IndexNow key file from functions/seo-config.js
 * and writes functions/_sitemap-meta.js with the deploy lastmod.
 */
import { createHash, randomBytes } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const CONFIG_DIR = join(ROOT, "config");
const DIST = join(ROOT, "dist");
const KEY_PATH = join(CONFIG_DIR, "indexnow.key");

mkdirSync(CONFIG_DIR, { recursive: true });
mkdirSync(DIST, { recursive: true });

if (!existsSync(KEY_PATH)) {
  writeFileSync(KEY_PATH, randomBytes(16).toString("hex") + "\n", "utf8");
  console.log("Created", KEY_PATH);
}

const indexNowKey = readFileSync(KEY_PATH, "utf8").trim();
if (!/^[a-zA-Z0-9-]{8,128}$/.test(indexNowKey)) {
  throw new Error("Invalid IndexNow key in config/indexnow.key");
}

const seoMod = await import(pathToFileURL(join(ROOT, "functions/seo-config.js")).href);
const libMod = await import(pathToFileURL(join(ROOT, "functions/sitemap-lib.js")).href);

const lastmod = process.env.SITEMAP_LASTMOD || new Date().toISOString().slice(0, 10);
const xml = libMod.buildSitemapXml(lastmod);
const entries = libMod.listSitemapEntries(lastmod);
const fingerprint = createHash("sha256")
  .update(entries.map((e) => e.loc).join("\n") + "\n" + lastmod)
  .digest("hex");

writeFileSync(join(ROOT, "config", "sitemap.generated.xml"), xml, "utf8");
writeFileSync(join(DIST, `${indexNowKey}.txt`), `${indexNowKey}\n`, "utf8");

// Prefer the Pages Function at /sitemap.xml over a static file (Functions can lose to
// static assets depending on deploy ordering). Remove any stale static copy.
try {
  const { unlinkSync } = await import("node:fs");
  unlinkSync(join(DIST, "sitemap.xml"));
} catch {
  /* no static sitemap — good */
}

writeFileSync(
  join(ROOT, "functions/_sitemap-meta.js"),
  `/** Auto-generated by scripts/generate-sitemap.mjs — do not edit. */
export const SITEMAP_LASTMOD = ${JSON.stringify(lastmod)};
export const SITEMAP_FINGERPRINT = ${JSON.stringify(fingerprint)};
export const INDEXNOW_KEY_PUBLIC = ${JSON.stringify(indexNowKey)};
export const SITEMAP_URL_COUNT = ${entries.length};
`,
  "utf8",
);

// Keep robots.txt pointing at the live sitemap.
writeFileSync(
  join(DIST, "robots.txt"),
  `User-agent: *
Allow: /

# Primary sitemap for Cloudflare Pages
Sitemap: ${seoMod.SITE_ORIGIN}/sitemap.xml
`,
  "utf8",
);

console.log(`sitemap.xml → ${entries.length} URLs, lastmod=${lastmod}`);
console.log(`IndexNow key file → dist/${indexNowKey}.txt`);
console.log(`fingerprint=${fingerprint.slice(0, 12)}…`);
