#!/usr/bin/env node
/**
 * Regenerates static dist/sitemap.xml (Google Search Console), snapshots,
 * IndexNow key file, robots.txt, and _sitemap-meta.js from seo-config.js.
 */
import { createHash, randomBytes } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const CONFIG_DIR = join(ROOT, "config");
const DIST = join(ROOT, "dist");
const KEY_PATH = join(CONFIG_DIR, "indexnow.key");

mkdirSync(CONFIG_DIR, { recursive: true });
mkdirSync(DIST, { recursive: true });

if (!existsSync(KEY_PATH)) {
  writeFileSync(KEY_PATH, randomBytes(16).toString("hex") + "\n", "utf8");
  console.log("Created", KEY_PATH);
}

const indexNowKey = readFileSync(KEY_PATH, "utf8").trim();
if (!/^[a-zA-Z0-9-]{8,128}$/.test(indexNowKey)) {
  throw new Error("Invalid IndexNow key in config/indexnow.key");
}

const seoMod = await import(pathToFileURL(join(ROOT, "functions/seo-config.js")).href);
const libMod = await import(pathToFileURL(join(ROOT, "functions/sitemap-lib.js")).href);

const lastmod = process.env.SITEMAP_LASTMOD || new Date().toISOString().slice(0, 10);
const pagesXml = libMod.buildPagesSitemapXml(lastmod);
const imagesXml = libMod.buildImagesSitemapXml(lastmod);
const entries = libMod.listSitemapEntries(lastmod);
const fingerprint = createHash("sha256")
  .update(entries.map((e) => e.loc).join("\n") + "\n" + lastmod)
  .digest("hex");

// Static files — served directly by Cloudflare Pages (most reliable for Googlebot).
writeFileSync(join(DIST, "sitemap.xml"), pagesXml, "utf8");
writeFileSync(join(DIST, "sitemap-images.xml"), imagesXml, "utf8");

writeFileSync(join(CONFIG_DIR, "sitemap.generated.xml"), pagesXml, "utf8");
writeFileSync(join(CONFIG_DIR, "sitemap-images.generated.xml"), imagesXml, "utf8");
writeFileSync(join(DIST, `${indexNowKey}.txt`), `${indexNowKey}\n`, "utf8");

writeFileSync(
  join(ROOT, "functions/_sitemap-meta.js"),
  `/** Auto-generated by scripts/generate-sitemap.mjs — do not edit. */
export const SITEMAP_LASTMOD = ${JSON.stringify(lastmod)};
export const SITEMAP_FINGERPRINT = ${JSON.stringify(fingerprint)};
export const INDEXNOW_KEY_PUBLIC = ${JSON.stringify(indexNowKey)};
export const SITEMAP_URL_COUNT = ${entries.length};
export const SITEMAP_INDEX_URL = ${JSON.stringify(`${seoMod.SITE_ORIGIN}/sitemap.xml`)};
export const SITEMAP_PAGES_URL = ${JSON.stringify(`${seoMod.SITE_ORIGIN}/sitemap.xml`)};
export const SITEMAP_IMAGES_URL = ${JSON.stringify(`${seoMod.SITE_ORIGIN}/sitemap-images.xml`)};
`,
  "utf8",
);

writeFileSync(
  join(DIST, "robots.txt"),
  `# https://billmaniac.win robots.txt
User-agent: *
Allow: /
Disallow: /api/
Disallow: /cdn-cgi/

# Submit in Google Search Console: ${seoMod.SITE_ORIGIN}/sitemap.xml
Sitemap: ${seoMod.SITE_ORIGIN}/sitemap.xml
`,
  "utf8",
);

console.log(`Static sitemap → dist/sitemap.xml (${entries.length} URLs, lastmod=${lastmod})`);
console.log(`Static image sitemap → dist/sitemap-images.xml`);
console.log(`Submit in GSC: ${seoMod.SITE_ORIGIN}/sitemap.xml`);
console.log(`IndexNow key file → dist/${indexNowKey}.txt`);
console.log(`fingerprint=${fingerprint.slice(0, 12)}…`);
