#!/usr/bin/env node
/**
 * Regenerates static dist/sitemap.xml (Google Search Console), snapshots,
 * IndexNow key file, robots.txt, and _sitemap-meta.js from seo-config.js.
 */
import { createHash, randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync, mkdirSync, unlinkSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const CONFIG_DIR = join(ROOT, "config");
const DIST = join(ROOT, "dist");
const KEY_PATH = join(CONFIG_DIR, "indexnow.key");

mkdirSync(CONFIG_DIR, { recursive: true });
mkdirSync(DIST, { recursive: true });

if (!existsSync(KEY_PATH)) {
  writeFileSync(KEY_PATH, randomBytes(16).toString("hex") + "\n", "utf8");
  console.log("Created", KEY_PATH);
}

const indexNowKey = readFileSync(KEY_PATH, "utf8").trim();
if (!/^[a-zA-Z0-9-]{8,128}$/.test(indexNowKey)) {
  throw new Error("Invalid IndexNow key in config/indexnow.key");
}

const seoMod = await import(pathToFileURL(join(ROOT, "functions/seo-config.js")).href);
const libMod = await import(pathToFileURL(join(ROOT, "functions/sitemap-lib.js")).href);

const lastmod = process.env.SITEMAP_LASTMOD || new Date().toISOString().slice(0, 10);
const pagesXml = libMod.buildPagesSitemapXml(lastmod);
const imagesXml = libMod.buildImagesSitemapXml(lastmod);
const entries = libMod.listSitemapEntries(lastmod);
const fingerprint = createHash("sha256")
  .update(entries.map((e) => e.loc).join("\n") + "\n" + lastmod)
  .digest("hex");

// Static files — served directly by Cloudflare Pages (most reliable for Googlebot).
writeFileSync(join(DIST, seoMod.SITEMAP_PAGES_FILE), pagesXml, "utf8");
writeFileSync(join(DIST, seoMod.SITEMAP_IMAGES_FILE), imagesXml, "utf8");
for (const legacy of ["sitemap1.xml", "sitemap-1.xml"]) {
  const legacyPath = join(DIST, legacy);
  if (existsSync(legacyPath)) unlinkSync(legacyPath);
}

writeFileSync(join(CONFIG_DIR, "sitemap.generated.xml"), pagesXml, "utf8");
writeFileSync(join(CONFIG_DIR, "sitemap-images.generated.xml"), imagesXml, "utf8");

const htmlLinks = entries
  .map(
    (e) =>
      `    <li><a href="${e.loc.replace(/"/g, "&quot;")}">${e.loc.replace(/&/g, "&amp;").replace(/</g, "&lt;")}</a></li>`,
  )
  .join("\n");
const htmlSitemap = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Site map — Bill Maniac</title>
  <meta name="robots" content="index, follow">
  <link rel="canonical" href="${seoMod.SITE_ORIGIN}/site-map">
</head>
<body>
  <main>
    <h1>Bill Maniac site map</h1>
    <p>HTML overview of public pages (updated ${lastmod}). XML feed: <a href="${seoMod.SITEMAP_PAGES_URL}">${seoMod.SITEMAP_PAGES_URL}</a></p>
    <ul>
${htmlLinks}
    </ul>
  </main>
</body>
</html>
`;
writeFileSync(join(DIST, "site-map.html"), htmlSitemap, "utf8");

writeFileSync(join(DIST, `${indexNowKey}.txt`), `${indexNowKey}\n`, "utf8");

writeFileSync(
  join(ROOT, "functions/_sitemap-meta.js"),
  `/** Auto-generated by scripts/generate-sitemap.mjs — do not edit. */
export const SITEMAP_LASTMOD = ${JSON.stringify(lastmod)};
export const SITEMAP_FINGERPRINT = ${JSON.stringify(fingerprint)};
export const INDEXNOW_KEY_PUBLIC = ${JSON.stringify(indexNowKey)};
export const SITEMAP_URL_COUNT = ${entries.length};
export const SITEMAP_INDEX_URL = ${JSON.stringify(seoMod.SITEMAP_PAGES_URL)};
export const SITEMAP_PAGES_URL = ${JSON.stringify(seoMod.SITEMAP_PAGES_URL)};
export const SITEMAP_IMAGES_URL = ${JSON.stringify(seoMod.SITEMAP_IMAGES_URL)};
`,
  "utf8",
);

writeFileSync(
  join(DIST, "robots.txt"),
  `# https://billmaniac.win robots.txt
User-agent: *
Allow: /
Disallow: /api/
Disallow: /cdn-cgi/

# Submit in Google Search Console (no trailing slash):
# ${seoMod.SITEMAP_PAGES_URL}
Sitemap: ${seoMod.SITEMAP_PAGES_URL}
`,
  "utf8",
);

const routesPath = join(DIST, "_routes.json");
const routes = existsSync(routesPath)
  ? JSON.parse(readFileSync(routesPath, "utf8"))
  : { version: 1, include: ["/*"], exclude: [] };
// Bypass Pages Functions for XML feeds — static + _headers is more reliable for
// Googlebot than functions/sitemap.xml.js (some edges returned HTTP 500).
const routeExcludes = new Set([
  ...(routes.exclude || []),
  "/pics/*",
  "/robots.txt",
  `/${seoMod.SITEMAP_PAGES_FILE}`,
  `/${seoMod.SITEMAP_IMAGES_FILE}`,
  "/manifest.json",
  "/metadata.json",
  "/site-map",
  "/site-map.html",
  "/*.txt",
  "/_headers",
  "/_redirects",
]);
routes.exclude = [...routeExcludes];
writeFileSync(routesPath, `${JSON.stringify(routes, null, 2)}\n`, "utf8");

const redirectsPath = join(DIST, "_redirects");
const redirectLines = existsSync(redirectsPath)
  ? readFileSync(redirectsPath, "utf8").split("\n")
  : [];
const sitemapRedirectBlock = [
  "# Legacy sitemap URLs → canonical feed (submit /sitemap.xml in GSC, no trailing slash)",
  "/sitemap1.xml https://billmaniac.win/sitemap.xml 301",
  "/sitemap-1.xml https://billmaniac.win/sitemap.xml 301",
  "/sitemap.xml/ https://billmaniac.win/sitemap.xml 301",
  "/sitemap-images.xml/ https://billmaniac.win/sitemap-images.xml 301",
];
const withoutSitemapRedirects = redirectLines.filter(
  (line) =>
    !line.startsWith("/sitemap1.xml ") &&
    !line.startsWith("/sitemap-1.xml ") &&
    !line.startsWith("/sitemap.xml/ ") &&
    !line.startsWith("/sitemap-images.xml/ ") &&
    !line.includes("Legacy sitemap URLs"),
);
const spaStart = withoutSitemapRedirects.findIndex((line) =>
  line.includes("Cloudflare Pages — clean URL SPA fallback"),
);
const tail =
  spaStart >= 0 ? withoutSitemapRedirects.slice(spaStart) : withoutSitemapRedirects.filter(Boolean);
writeFileSync(redirectsPath, [...sitemapRedirectBlock, "", ...tail].join("\n"), "utf8");

console.log(`Static sitemap → dist/${seoMod.SITEMAP_PAGES_FILE} (${entries.length} URLs, lastmod=${lastmod})`);
console.log(`Static HTML sitemap → dist/site-map.html (public URL /site-map)`);
console.log(`Static image sitemap → dist/${seoMod.SITEMAP_IMAGES_FILE}`);
console.log(`Submit in GSC: ${seoMod.SITEMAP_PAGES_URL}`);
console.log(`IndexNow key file → dist/${indexNowKey}.txt`);
console.log(`fingerprint=${fingerprint.slice(0, 12)}…`);
